# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('picture', models.ImageField(upload_to='uploads/pictures/')),
                ('resume', models.FileField(upload_to='uploads/resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfirstapp.StudentProfile')),
            ],
        ),
        migrations.AddField(
            model_name='studentlinks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfirstapp.StudentProfile'),
        ),
        migrations.AddField(
            model_name='studentinterest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfirstapp.StudentProfile'),
        ),
    ]
